### ISSUE TITLE
Use of `claim` crate causes dependency conflicts

### ISSUE THREAD

**Issue by SludgePhD** [rgeometry/rgeometry#87]
See https://github.com/svartalf/rust-claim/issues/9

This makes it impossible to use rgeometry together with `nix`, for example, which I want to do.

A possible workaround for users is to patch the (seemingly unmaintained) dependency like this:

```toml
[patch.crates-io]
claim = { git = "https://github.com/Turbo87/rust-claim.git", rev = "23892a3" }
```
